"""change dirty column length

Revision ID: 0de2977d75e9
Revises: 52dfec97c557
Create Date: 2023-11-15 21:34:33.951507

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0de2977d75e9'
down_revision: Union[str, None] = '52dfec97c557'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'dirty',
                    existing_type=mysql.VARCHAR(length=1),
                    type_=sa.String(length=10),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'dirty',
                    existing_type=sa.String(length=10),
                    type_=mysql.VARCHAR(length=1),
                    existing_nullable=True)
    # ### end Alembic commands ###
