"""change version column type

Revision ID: 38fbc03521de
Revises: 0de2977d75e9
Create Date: 2023-11-15 21:35:24.061341

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '38fbc03521de'
down_revision: Union[str, None] = '0de2977d75e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'version',
                    existing_type=mysql.INTEGER(display_width=11),
                    type_=sa.String(length=20),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'version',
                    existing_type=sa.String(length=20),
                    type_=mysql.INTEGER(display_width=11),
                    existing_nullable=True)
    # ### end Alembic commands ###
