"""change uix_name_card_no to uidx_name_card_no

Revision ID: 3a1544b425ba
Revises: 7539e9cf1d5b
Create Date: 2023-11-15 22:07:40.422248

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3a1544b425ba'
down_revision: Union[str, None] = '7539e9cf1d5b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_name_card_no', table_name='personal_info')
    op.create_index('uidx_name_card_no', 'personal_info',
                    ['name', 'card_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('uix_name_card_no', 'personal_info',
                    ['name', 'card_no'], unique=True)
    op.drop_index('uidx_name_card_no', table_name='personal_info')
    # ### end Alembic commands ###
