"""change birthday type

Revision ID: 52dfec97c557
Revises: a4490d293d13
Create Date: 2023-11-15 21:33:11.812582

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '52dfec97c557'
down_revision: Union[str, None] = 'a4490d293d13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'birthday',
                    existing_type=sa.DATE(),
                    type_=sa.String(length=8),
                    existing_comment='生日',
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'birthday',
                    existing_type=sa.String(length=8),
                    type_=sa.DATE(),
                    existing_comment='生日',
                    existing_nullable=True)
    # ### end Alembic commands ###
