"""change mobile,tel column length

Revision ID: 7539e9cf1d5b
Revises: 090aece45245
Create Date: 2023-11-15 21:39:11.796756

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7539e9cf1d5b'
down_revision: Union[str, None] = '090aece45245'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'mobile',
                    existing_type=mysql.VARCHAR(length=20),
                    type_=sa.String(length=40),
                    existing_comment='手机',
                    existing_nullable=True)
    op.alter_column('personal_info', 'tel',
                    existing_type=mysql.VARCHAR(length=20),
                    type_=sa.String(length=40),
                    existing_comment='电话',
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'tel',
                    existing_type=sa.String(length=40),
                    type_=mysql.VARCHAR(length=20),
                    existing_comment='电话',
                    existing_nullable=True)
    op.alter_column('personal_info', 'mobile',
                    existing_type=sa.String(length=40),
                    type_=mysql.VARCHAR(length=20),
                    existing_comment='手机',
                    existing_nullable=True)
    # ### end Alembic commands ###
