"""Add UniqueConstraint uix_name_card_no and some comments

Revision ID: 88f8e4ec4567
Revises: bf2baeed0499
Create Date: 2023-11-15 18:31:31.823855

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '88f8e4ec4567'
down_revision: Union[str, None] = 'bf2baeed0499'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'name',
                    existing_type=mysql.VARCHAR(length=255),
                    comment='姓名',
                    existing_nullable=True)
    op.alter_column('personal_info', 'card_no',
                    existing_type=mysql.VARCHAR(length=255),
                    comment='身份证号',
                    existing_nullable=True)
    op.alter_column('personal_info', 'gender',
                    existing_type=mysql.VARCHAR(length=1),
                    comment='性别',
                    existing_nullable=True)
    op.alter_column('personal_info', 'birthday',
                    existing_type=sa.DATE(),
                    comment='生日',
                    existing_nullable=True)
    op.alter_column('personal_info', 'address',
                    existing_type=mysql.VARCHAR(length=255),
                    comment='住址',
                    existing_nullable=True)
    op.alter_column('personal_info', 'mobile',
                    existing_type=mysql.VARCHAR(length=20),
                    comment='手机',
                    existing_nullable=True)
    op.alter_column('personal_info', 'tel',
                    existing_type=mysql.VARCHAR(length=20),
                    comment='电话',
                    existing_nullable=True)
    op.alter_column('personal_info', 'email',
                    existing_type=mysql.VARCHAR(length=255),
                    comment='邮箱',
                    existing_nullable=True)
    op.alter_column('personal_info', 'nation',
                    existing_type=mysql.VARCHAR(length=255),
                    comment='民族',
                    existing_nullable=True)
    op.alter_column('personal_info', 'education',
                    existing_type=mysql.VARCHAR(length=255),
                    comment='学历',
                    existing_nullable=True)
    op.alter_column('personal_info', 'company',
                    existing_type=mysql.VARCHAR(length=255),
                    comment='公司',
                    existing_nullable=True)
    op.alter_column('personal_info', 'created_at',
                    existing_type=mysql.TIMESTAMP(),
                    comment='插入时间',
                    existing_nullable=True,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))  # type: ignore # noqa:E501
    op.alter_column('personal_info', 'updated_at',
                    existing_type=mysql.TIMESTAMP(),
                    comment='更新时间',
                    existing_nullable=False,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))  # type: ignore # noqa:E501
    op.create_index('uix_name_card_no', 'personal_info',
                    ['name', 'card_no'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uix_name_card_no', table_name='personal_info')
    op.alter_column('personal_info', 'updated_at',
                    existing_type=mysql.TIMESTAMP(),
                    comment=None,
                    existing_comment='更新时间',
                    existing_nullable=False,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))  # type: ignore # noqa:E501
    op.alter_column('personal_info', 'created_at',
                    existing_type=mysql.TIMESTAMP(),
                    comment=None,
                    existing_comment='插入时间',
                    existing_nullable=True,
                    existing_server_default=sa.text('CURRENT_TIMESTAMP'))  # type: ignore # noqa:E501
    op.alter_column('personal_info', 'company',
                    existing_type=mysql.VARCHAR(length=255),
                    comment=None,
                    existing_comment='公司',
                    existing_nullable=True)
    op.alter_column('personal_info', 'education',
                    existing_type=mysql.VARCHAR(length=255),
                    comment=None,
                    existing_comment='学历',
                    existing_nullable=True)
    op.alter_column('personal_info', 'nation',
                    existing_type=mysql.VARCHAR(length=255),
                    comment=None,
                    existing_comment='民族',
                    existing_nullable=True)
    op.alter_column('personal_info', 'email',
                    existing_type=mysql.VARCHAR(length=255),
                    comment=None,
                    existing_comment='邮箱',
                    existing_nullable=True)
    op.alter_column('personal_info', 'tel',
                    existing_type=mysql.VARCHAR(length=20),
                    comment=None,
                    existing_comment='电话',
                    existing_nullable=True)
    op.alter_column('personal_info', 'mobile',
                    existing_type=mysql.VARCHAR(length=20),
                    comment=None,
                    existing_comment='手机',
                    existing_nullable=True)
    op.alter_column('personal_info', 'address',
                    existing_type=mysql.VARCHAR(length=255),
                    comment=None,
                    existing_comment='住址',
                    existing_nullable=True)
    op.alter_column('personal_info', 'birthday',
                    existing_type=sa.DATE(),
                    comment=None,
                    existing_comment='生日',
                    existing_nullable=True)
    op.alter_column('personal_info', 'gender',
                    existing_type=mysql.VARCHAR(length=1),
                    comment=None,
                    existing_comment='性别',
                    existing_nullable=True)
    op.alter_column('personal_info', 'card_no',
                    existing_type=mysql.VARCHAR(length=255),
                    comment=None,
                    existing_comment='身份证号',
                    existing_nullable=True)
    op.alter_column('personal_info', 'name',
                    existing_type=mysql.VARCHAR(length=255),
                    comment=None,
                    existing_comment='姓名',
                    existing_nullable=True)
    # ### end Alembic commands ###
