"""add fax column comment and change fax column length

Revision ID: 8fa65d8e0a15
Revises: 95c8a80805e9
Create Date: 2023-11-15 22:50:03.912506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8fa65d8e0a15'
down_revision: Union[str, None] = '95c8a80805e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'fax',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=70),
               comment='传真',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'fax',
               existing_type=sa.String(length=70),
               type_=mysql.VARCHAR(length=20),
               comment=None,
               existing_comment='传真',
               existing_nullable=True)
    # ### end Alembic commands ###
