"""change mobile,tel column length

Revision ID: 95c8a80805e9
Revises: 3a1544b425ba
Create Date: 2023-11-15 22:22:33.258444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '95c8a80805e9'
down_revision: Union[str, None] = '3a1544b425ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'mobile',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=60),
               existing_comment='手机',
               existing_nullable=True)
    op.alter_column('personal_info', 'tel',
               existing_type=mysql.VARCHAR(length=20),
               type_=sa.String(length=60),
               existing_comment='电话',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'tel',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=20),
               existing_comment='电话',
               existing_nullable=True)
    op.alter_column('personal_info', 'mobile',
               existing_type=sa.String(length=60),
               type_=mysql.VARCHAR(length=20),
               existing_comment='手机',
               existing_nullable=True)
    # ### end Alembic commands ###
