"""change gender column length

Revision ID: a4490d293d13
Revises: 88f8e4ec4567
Create Date: 2023-11-15 21:26:52.721482

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import mysql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a4490d293d13'
down_revision: Union[str, None] = '88f8e4ec4567'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'gender',
                    existing_type=mysql.VARCHAR(length=1),
                    type_=sa.String(length=10),
                    existing_comment='性别',
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('personal_info', 'gender',
                    existing_type=sa.String(length=10),
                    type_=mysql.VARCHAR(length=1),
                    existing_comment='性别',
                    existing_nullable=True)
    # ### end Alembic commands ###
